# Generated by Django 5.1.5 on 2025-03-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('no_of_ratings', models.IntegerField(default=0)),
                ('ratings', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
    ]
