# Generated by Django 5.1.5 on 2025-04-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_rename_user_driver_id'),
        ('user', '0006_rename_profile_picture_url_userprofile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user'),
        ),
    ]
