# Generated by Django 5.1.5 on 2025-04-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='user_id',
            new_name='driver',
        ),
    ]
