# Generated by Django 5.1.5 on 2025-05-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_rename_user_id_vehicle_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=255),
        ),
    ]
