# Generated by Django 5.1.5 on 2025-04-23 17:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0004_vehicle'),
        ('user', '0006_rename_profile_picture_url_userprofile_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lat', models.FloatField()),
                ('source_lng', models.FloatField()),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('available_seats', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField(default=0)),
                ('preferred_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any')),
                ('payment_option', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Any', 'Any')], default='Any')),
                ('expiration_time', models.DateTimeField()),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('riders', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Array of rider user IDs', size=None)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_rides', to='user.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='driver.vehicle')),
            ],
            options={
                'db_table': 'ride',
            },
        ),
    ]
