# Generated by Django 5.1.5 on 2025-04-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-id']},
        ),
    ]
