# Generated by Django 5.1.5 on 2025-04-25 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
        ('user', '0006_rename_profile_picture_url_userprofile_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='RideHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lat', models.FloatField()),
                ('source_lng', models.FloatField()),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('riderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_history', to='user.user')),
            ],
        ),
    ]
