# Generated by Django 5.1.5 on 2025-04-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_riderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='expiration_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='pickup_time',
            field=models.TimeField(),
        ),
    ]
