# Generated by Django 5.1.5 on 2025-05-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_alter_ride_options_ridehistory'),
        ('ride', '0005_alter_riderequest_status'),
    ]

    operations = [
    ]
