# Generated by Django 5.1.5 on 2025-04-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
        ('user', '0006_rename_profile_picture_url_userprofile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user'),
        ),
    ]
