# Generated by Django 5.1.5 on 2025-03-25 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('profile_picture_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
