# Generated by Django 5.1.5 on 2025-03-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture_url',
            new_name='url',
        ),
    ]
